import * as vscode from 'vscode';
import { KimiService } from './kimiService';

let kimiService: KimiService;

export function activate(context: vscode.ExtensionContext) {
	console.log('Kimi AI Worker extension activated');

	kimiService = new KimiService();

	// ── Generate Code ──────────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.generateCode', async () => {
			const editor = vscode.window.activeTextEditor;

			// If there's a selection, use it as context; otherwise ask for a prompt
			const selectedText = editor
				? editor.document.getText(editor.selection)
				: '';

			const prompt = await vscode.window.showInputBox({
				placeHolder: 'e.g. A React hook that fetches paginated data',
				prompt: 'Describe the code you want Kimi to generate',
				value: selectedText || undefined,
				ignoreFocusOut: true,
			});

			if (!prompt) { return; }

			const language = await vscode.window.showQuickPick(
				['TypeScript', 'JavaScript', 'Python', 'Go', 'Rust', 'Java', 'C#', 'C++', 'PHP', 'Other'],
				{ placeHolder: 'Select target language' }
			);

			if (!language) { return; }

			await withProgress('Kimi AI: Generating code…', async () => {
				try {
					const result = await kimiService.generateCode({
						prompt,
						language,
						context: selectedText || undefined,
					});

					const doc = await vscode.workspace.openTextDocument({
						language: languageId(language),
						content: result.code,
					});

					await vscode.window.showTextDocument(doc, { preview: false });
					vscode.window.showInformationMessage('✅ Code generated by Kimi K2.6!');
				} catch (err) {
					handleError(err);
				}
			});
		})
	);

	// ── Explain Code ───────────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.explainCode', async () => {
			const code = getSelectedText();
			if (!code) { return; }

			await withProgress('Kimi AI: Analysing code…', async () => {
				try {
					const explanation = await kimiService.explainCode(code);
					showInPanel('Kimi AI – Explanation', explanation);
					vscode.window.showInformationMessage('✅ Explanation ready!');
				} catch (err) {
					handleError(err);
				}
			});
		})
	);

	// ── Refactor Code ──────────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.refactorCode', async () => {
			const editor = vscode.window.activeTextEditor;
			if (!editor) { vscode.window.showErrorMessage('No active editor'); return; }

			const selection = editor.selection;
			const code = editor.document.getText(selection);
			if (!code) { vscode.window.showErrorMessage('No text selected'); return; }

			await withProgress('Kimi AI: Refactoring…', async () => {
				try {
					const refactored = await kimiService.refactorCode(code, editor.document.languageId);
					await editor.edit(b => b.replace(selection, refactored));
					vscode.window.showInformationMessage('✅ Code refactored!');
				} catch (err) {
					handleError(err);
				}
			});
		})
	);

	// ── Generate Tests ─────────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.generateTests', async () => {
			const editor = vscode.window.activeTextEditor;
			if (!editor) { vscode.window.showErrorMessage('No active editor'); return; }

			const code = editor.document.getText(editor.selection);
			if (!code) { vscode.window.showErrorMessage('No text selected'); return; }

			await withProgress('Kimi AI: Generating tests…', async () => {
				try {
					const tests = await kimiService.generateTests(code, editor.document.languageId);
					const doc = await vscode.workspace.openTextDocument({
						language: editor.document.languageId,
						content: tests,
					});
					await vscode.window.showTextDocument(doc, { preview: false });
					vscode.window.showInformationMessage('✅ Tests generated!');
				} catch (err) {
					handleError(err);
				}
			});
		})
	);

	// ── Fix Bugs ───────────────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.fixBugs', async () => {
			const editor = vscode.window.activeTextEditor;
			if (!editor) { vscode.window.showErrorMessage('No active editor'); return; }

			const selection = editor.selection;
			const code = editor.document.getText(selection);
			if (!code) { vscode.window.showErrorMessage('No text selected'); return; }

			const errorMessage = await vscode.window.showInputBox({
				placeHolder: 'Paste the error message (optional)',
				prompt: 'Error message to help Kimi understand the bug',
				ignoreFocusOut: true,
			});

			await withProgress('Kimi AI: Fixing bugs…', async () => {
				try {
					const fixed = await kimiService.fixBugs(code, editor.document.languageId, errorMessage);
					await editor.edit(b => b.replace(selection, fixed));
					vscode.window.showInformationMessage('✅ Bugs fixed!');
				} catch (err) {
					handleError(err);
				}
			});
		})
	);

	// ── Add Documentation ──────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.addDocumentation', async () => {
			const editor = vscode.window.activeTextEditor;
			if (!editor) { vscode.window.showErrorMessage('No active editor'); return; }

			const selection = editor.selection;
			const code = editor.document.getText(selection);
			if (!code) { vscode.window.showErrorMessage('No text selected'); return; }

			await withProgress('Kimi AI: Adding documentation…', async () => {
				try {
					const documented = await kimiService.addDocumentation(code, editor.document.languageId);
					await editor.edit(b => b.replace(selection, documented));
					vscode.window.showInformationMessage('✅ Documentation added!');
				} catch (err) {
					handleError(err);
				}
			});
		})
	);

	// ── Configure ──────────────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.configureApiKey', async () => {
			const cfg = vscode.workspace.getConfiguration('kimi-ai');

			const accountId = await vscode.window.showInputBox({
				prompt: 'Enter your Cloudflare Account ID',
				value: cfg.get<string>('cloudflareAccountId', ''),
				ignoreFocusOut: true,
				validateInput: v => (v ? null : 'Account ID is required'),
			});
			if (accountId === undefined) { return; }

			const apiToken = await vscode.window.showInputBox({
				prompt: 'Enter your Cloudflare Workers AI API Token',
				value: cfg.get<string>('cloudflareApiToken', ''),
				password: true,
				ignoreFocusOut: true,
				validateInput: v => (v ? null : 'API Token is required'),
			});
			if (apiToken === undefined) { return; }

			const model = await vscode.window.showQuickPick(
				[
					{ label: '@cf/moonshotai/kimi-k2.6', description: 'Kimi K2.6 (recommended)' },
					{ label: '@cf/moonshotai/kimi-k2.5', description: 'Kimi K2.5' },
					{ label: '@cf/meta/llama-3.3-70b-instruct-fp8-fast', description: 'Llama 3.3 70B' },
					{ label: '@cf/qwen/qwen2.5-coder-32b-instruct', description: 'Qwen 2.5 Coder 32B' },
				],
				{ placeHolder: 'Select Workers AI model' }
			);
			if (!model) { return; }

			await cfg.update('cloudflareAccountId', accountId, vscode.ConfigurationTarget.Global);
			await cfg.update('cloudflareApiToken', apiToken, vscode.ConfigurationTarget.Global);
			await cfg.update('model', model.label, vscode.ConfigurationTarget.Global);

			kimiService = new KimiService(); // reload with new config
			vscode.window.showInformationMessage(`✅ Kimi AI configured with ${model.label}`);
		})
	);

	// ── Test Connection ────────────────────────────────────────────────────────
	context.subscriptions.push(
		vscode.commands.registerCommand('kimi-ai.testConnection', async () => {
			await withProgress('Kimi AI: Testing connection…', async () => {
				try {
					const ok = await kimiService.testConnection();
					if (ok) {
						vscode.window.showInformationMessage('✅ Connected to Kimi K2.6 via Cloudflare Workers AI!');
					} else {
						vscode.window.showWarningMessage('⚠️ Connection test returned an empty response.');
					}
				} catch (err) {
					handleError(err);
				}
			});
		})
	);
}

export function deactivate() {}

// ── Helpers ────────────────────────────────────────────────────────────────────

function getSelectedText(): string | undefined {
	const editor = vscode.window.activeTextEditor;
	if (!editor) { vscode.window.showErrorMessage('No active editor'); return undefined; }
	const text = editor.document.getText(editor.selection);
	if (!text) { vscode.window.showErrorMessage('No text selected'); return undefined; }
	return text;
}

async function withProgress(title: string, task: () => Promise<void>): Promise<void> {
	await vscode.window.withProgress(
		{ location: vscode.ProgressLocation.Notification, title, cancellable: false },
		async () => task()
	);
}

function showInPanel(title: string, content: string): void {
	const channel = vscode.window.createOutputChannel(title);
	channel.clear();
	channel.appendLine(content);
	channel.show(true);
}

function handleError(err: unknown): void {
	const msg = err instanceof Error ? err.message : String(err);
	vscode.window.showErrorMessage(`❌ Kimi AI: ${msg}`);
	console.error('[kimi-ai]', err);
}

function languageId(label: string): string {
	const map: Record<string, string> = {
		TypeScript: 'typescript',
		JavaScript: 'javascript',
		Python: 'python',
		Go: 'go',
		Rust: 'rust',
		Java: 'java',
		'C#': 'csharp',
		'C++': 'cpp',
		PHP: 'php',
		Other: 'plaintext',
	};
	return map[label] ?? 'plaintext';
}
